### ISSUE TITLE
Checklist do projeto (Full Dopamina)

### ISSUE THREAD

**Issue by phdosilva** [phdosilva/MetodosNumericos#1]
## Métodos

- [ ] **Euler**
    - [ ] Bônus: gerar gráfico.
- [ ] **Euler Inverso**
    - [ ] Bônus: resolva sem usar o método de previsão
    - [ ] Bônus: gerar gráfico.
- [ ] **Euler Aprimorado**
    - [ ] Bônus: resolva sem usar o método de previsão
    - [ ] Bônus: gere o gráfico
- [ ] **Runge-Kutta**
    - [ ] Bônus: faça runge-kutta para ordens mais altas.
    - [ ] Bônus: gere o gráfico
- [ ] **Adam-Bashforth**
    - [ ] Bônus: resolva sem usar o método de previsão
    - [ ] Bônus: calcule para ordem n
    - [ ] Bônus: gere o gráfico
- [ ] **Adam-Multon**
    - [ ] Bônus: utilize o método de previsão a partir de outros métodos além de bashforth
    - [ ] Bônus: resolva sem usar o método de previsão
    - [ ] Bônus: calcule para ordem n
    - [ ] Bônus: gere o gráfico
- [ ] **Fórmula Inversa**
    - [ ] Bônus: resolva sem usar o método de previsão
    - [ ] Bônus: calcule para ordem n
    - [ ] Bônus: gere o gráfico
## Bônus
- [ ] Implementem uma função que calcula para todos os métodos.
- [ ] Implementem uma função que compara todos os métodos e com os valores exatos.
